[package]
name = "breezy"
version = "3.3.4"
authors = [ "Martin Packman <gzlist@googlemail.com>", "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
publish = false
default-run = "brz"
license = "GPL-2.0+"
description = "Friendly distributed version control system"
repository = "https://code.launchpad.net/brz"
homepage = "https://www.breezy-vcs.org/"
documentation = "https://www.breezy-vcs.org/doc/"

[workspace]
members = ["crates/*"]

[[bin]]
name = "brz"
path = "breezy/main.rs"

[lib]

[features]
default = ["i18n", "pyo3"]
i18n = ["dep:gettext-rs"]
pyo3 = []

[dependencies]
pyo3 = ">=0.17, <0.19"
gettext-rs = { version = "0.7", optional = true }
log = "0.4"
breezy-osutils = { path = "crates/osutils" }
chrono = "0.4"
bazaar = { path = "crates/bazaar" }
percent-encoding = "2"
url = "2"
regex = "1"

[target.'cfg(unix)'.dependencies]
nix = ">=0.26"
