[package]
name = "breezy"
version = "3.4.0"
authors = [ "Martin Packman <gzlist@googlemail.com>", "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
default-run = "brz"
license = "GPL-2.0+"
description = "Friendly distributed version control system"
repository = "https://code.launchpad.net/brz"
homepage = "https://www.breezy-vcs.org/"
documentation = "https://www.breezy-vcs.org/doc/"
include = [
	"src/*.rs",
	"breezy/main.rs",
	"README.rst",
]

[workspace]
members = ["crates/*"]

[[bin]]
name = "brz"
path = "breezy/main.rs"

[lib]

[features]
default = ["i18n", "pyo3"]
i18n = ["dep:gettext-rs"]
pyo3 = []

[dependencies]
pyo3 = ">=0.19"
gettext-rs = { version = "0.7", optional = true }
log = "0.4"
breezy-osutils = { path = "crates/osutils", version = ">=3.3.4" }
chrono = "0.4"
bazaar = { path = "crates/bazaar" }
breezy-graph = { path = "crates/graph" }
percent-encoding = "2"
url = "2"
regex = "1"
inventory = "0.3"
lazy_static = "1.4"
once_cell = "1"
textwrap = ">=0.13"
serde_yaml = "0.9"
serde = { version = "1", features = ["derive"]}

[target.'cfg(unix)'.dependencies]
nix = ">=0.26"
