[build-system]
requires = [
    "packaging",
    "setuptools",
    "setuptools-gettext",
    "setuptools-rust",
    "configobj",
    "cython>=0.29",
    "pyyaml",
]
build-backend = "setuptools.build_meta"
