[build-system]
requires = [
    "packaging",
    "setuptools",
    "setuptools-rust",
    "configobj",
    "cython>=0.29",
    "pyyaml",
]

[tool.mypy]
python_version = "3.6"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
exclude = ['^breezy/util/simplemapi\.py$']
