[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]

[tool.mypy]
python_version = "3.6"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
exclude = [
    '^breezy/util/simplemapi\.py$'
]
