[package]
name = "bazaar"
version = "3.3.3"
authors = ["Martin Packman", "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2018"
description = "Rust implementation of the Bazaar formats and protocols"
license = "GPLv2+"
homepage = "https://www.breezy-vcs.org/"

[lib]

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.regex]
version = "1.5.4"
