[package]
name = "bazaar"
version = "3.3.3"
authors = [ "Martin Packman <gzlist@googlemail.com>", "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2018"
description = "Rust implementation of the Bazaar formats and protocols"
license = "GPL-2.0+"
homepage = "https://www.breezy-vcs.org/"

[lib]

[dependencies]
breezy-osutils = { path = "../osutils" }
lazy_static = "1.4.0"
regex = "1.3.1"
