[package]
name = "bazaar-rio"
version = "3.3.3"
edition = "2018"
description = "The RIO serialization format used by Bazaar"
license = "GPLv2+"

[lib]
crate-type = ["cdylib"]

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.regex]
version = "1.5.4"
