[package]
name = "bazaar-hashcache"
version = "3.3.3"
edition = "2018"
description = "The hashcache used by Bazaar"
license = "GPLv2+"

[lib]

[dependencies]
libc = "0.2"
sha1 = "0.10"
breezy-osutils = { path = "../osutils" }
bazaar = { path = "../bazaar" }
tempfile = "3"
log = "0.4"
