[package]
name = "bazaar-dirstate"
version = "3.3.3"
edition = "2018"
description = "The dirstate format used by Bazaar"
license = "GPLv2+"

[lib]

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.regex]
version = "1.5.4"
