[package]
name = "breezy-osutils"
version = "3.3.3"
edition = "2018"
description = "Low level OS wrappers for Breezy"
license = "GPL-2.0+"

[lib]

[dependencies]
memchr = "2.3.3"
walkdir = "2"
sha1 = "0.10.1"
unicode-normalization = "0.1.19"

[target.'cfg(target_os = "windows")'.dependencies]
lazy_static = "1.4.0"
